version: '2.0'

services:
  
  db:
    image: postgres:13.16
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users

  users_api:
    build: ./userAPI/src
    command: uvicorn main:app --reload  --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/users


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafanadocker 
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana


volumes:
  postgres_data:
  grafana:
  # grafana_data:
  #     driver: local
  #     driver_opts:
  #       o: bind
  #       type: none
  #       device: ./graf_data
