
#=============  Deployment ============================================================================================================
replicaCount: 1

image:
  repository: artvoropay/otus_order_ms
  tag: "0.2"

strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 3

imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

containerEnv:
    PG_SERVER: dbhost
    PG_PORT: dbport
    PG_USER: dbuser
    PG_PASSWORD: dbpass
    PG_DB: dbname
    RABBITMQ_HOST: rabbit_host
    RABBITMQ_PORT: rabbit_port
   

#=============  Service ============================================================================================================
service:
  type: NodePort
  port: 80
  owner: artem_voropay
  description: otus_hw8
  targetPort: 8000

#=============  Ingress ============================================================================================================
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: order-svc
                port:
                  number: 80
    
        


#=============  Secret ============================================================================================================

secrets:
  dbhost: b3JkZXItcG9zdGdyZXMtc2VydmljZQ==
  dbport: NTQzMg==
  dbuser: cG9zdGdyZXM=
  dbpass: cG9zdGdyZXM=
  dbname: b3JkZXI=
  # rabbit_host: MTkyLjE2OC4xMDEuMTA=
  # rabbit_port: MzE4MzM=
  rabbit_host: aHR0cDovL3JhYmJpdC1zdmMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
  rabbit_port: NTY3Mg==


# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

