apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-postgresdb-pv
  labels:
    type: local
spec:
  # storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/auth_pgdata"