version: '2.0'

services:
  
  db:
    image: postgres:13.16
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users

  users_api:
    build: ./authAPI/src
    command: uvicorn main:app --reload  --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/users
      -

volumes:
  postgres_data:
