apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-prometheus-server-pv
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: 
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"