
#=============  Deployment ============================================================================================================
replicaCount: 1

image:
  repository: artvoropay/otus_notify_ms
  tag: "0.2"

strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 3

imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

containerEnv:
    PG_SERVER: dbhost
    PG_PORT: dbport
    PG_USER: dbuser
    PG_PASSWORD: dbpass
    PG_DB: dbname
   

#=============  Service ============================================================================================================
service:
  type: NodePort
  owner: artem_voropay
  description: otus
  port: 80
  targetPort: 8000
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: metrics
    port: 9093
    targetPort: 8000

#=============  Ingress ============================================================================================================
ingress:
  enabled: true
  className: "nginx"
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - path: /notify
          pathType: ImplementationSpecific
          backend:
              service:
                name: notify-svc
                port:
                  number: 80
    

#=============  Service Monitor ============================================================================================================

serviceMonitor:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
       


#=============  Secret ============================================================================================================

secrets:
  dbhost: bm90aWZ5LXBvc3RncmVzLXNlcnZpY2U=
  dbport: NTQzMg==
  dbuser: cG9zdGdyZXM=
  dbpass: cG9zdGdyZXM=
  dbname: bm90aWZ5


# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

