{
 "title": "nginx-ingress",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total API Request",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{handler!~\"/health|/health/|/metrics\"})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{status=\"5xx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Controller Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (nginx_ingress_controller_requests{status=~\"500\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_requests_total{container=\"order\", handler!~\"/health|/health/|/metrics\"}[1m]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ingress-Controller Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Billing API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_requests_total{container=\"billing\", handler!~\"/health|/health/|/metrics\"}[1m]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_requests_total{container=\"auth\", handler!~\"/health|/health/|/metrics\"}[1m]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ingress Controller RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by(ingress) (rate(nginx_ingress_controller_requests{exported_service!~\"grafana-svc|prometheus-svc|rabbitmq-0\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notify API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_requests_total{container=\"notify\", handler!~\"/health|/health/|/metrics\"}[1m]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Delivery API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_requests_total{container=\"delivery\", handler!~\"/health|/health/|/metrics\"}[1m]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}