
#=============  Deployment ============================================================================================================
replicaCount: 1

image:
  repository: artvoropay/otus_order_ms
  tag: "0.4"

strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 3

imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

containerEnv:
    PG_SERVER: dbhost
    PG_PORT: dbport
    PG_USER: dbuser
    PG_PASSWORD: dbpass
    PG_DB: dbname
    NOTIFY_URL: notify_url
    RABBITMQ_HOST: rabbit_host
    RABBITMQ_PORT: rabbit_port
   

#=============  Service ============================================================================================================
service:
  type: NodePort
  owner: artem_voropay
  description: otus
  port: 80
  targetPort: 8000
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: metrics
    port: 9093
    targetPort: 8000


#=============  Ingress ============================================================================================================
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://auth-svc.default.svc.cluster.local/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-user-id,x-user-login"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: order-svc
                port:
                  number: 80
    
        
#=============  Service Monitor ============================================================================================================

serviceMonitor:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s

#=============  Secret ============================================================================================================

secrets:
  dbhost: b3JkZXItcG9zdGdyZXMtc2VydmljZQ==
  dbport: NTQzMg==
  dbuser: cG9zdGdyZXM=
  dbpass: cG9zdGdyZXM=
  dbname: b3JkZXI=
  # rabbit_host: MTkyLjE2OC4xMDEuMTA=
  # rabbit_port: MzE4MzM=
  notify_url:  aHR0cDovL25vdGlmeS1zdmMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
  rabbit_host: cmFiYml0LXN2Yy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  rabbit_port: NTY3Mg==


# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

