apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  namespace: default
  name: order-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: order
  endpoints:
  {{- range .Values.serviceMonitor.endpoints }}
    - port: {{ .port }}
      path: {{ .path }}
      interval: {{ .interval }}
    {{- end}}  