
#=============  Deployment ============================================================================================================
replicaCount: 1

image:
  repository: artvoropay/otus_billing_ms
  tag: "0.2"

strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 3

imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

containerEnv:
    PG_SERVER: dbhost
    PG_PORT: dbport
    PG_USER: dbuser
    PG_PASSWORD: dbpass
    PG_DB: dbname
   

#=============  Service ============================================================================================================
service:
  type: NodePort
  port: 80
  owner: artem_voropay
  description: otus_hw7
  targetPort: 8000

#=============  Ingress ============================================================================================================
ingress:
  enabled: true
  className: "nginx"
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - path: /billing
          pathType: Prefix
          backend:
              service:
                name: billing-svc
                port:
                  number: 80
    
        


#=============  Secret ============================================================================================================

secrets:
  dbhost: YmlsbGluZy1wb3N0Z3Jlcy1zZXJ2aWNl
  dbport: NTQzMg==
  dbuser: cG9zdGdyZXM=
  dbpass: cG9zdGdyZXM=
  dbname: YmlsbGluZw==


# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

