apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  namespace: default
  name: users-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ms-users
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s